### ISSUE TITLE
Linting.

### ISSUE THREAD

**Issue by CyberiumShadow** [eslachance/komada-pieces#24]
We're gonna need a good linter that isn't too strict like the default AirBnB one and one that isn't too slack like the ESlint-recommended.

I'm getting a headache from the Air-BnB linter.

THoughts on this one? https://github.com/CyberiumShadow/selfbot/blob/review/.eslintrc.json

@hkwu

**Comment by hkwu** [comment]
Where'd you get all those rules from? 🤔

But anyways I think the Airbnb rules can work, I'll edit some of the rules so it's not going to hand out 500 errors like it did before. Plus we have the benefit of being able to get new rules when the npm package is updated.

**Comment by CyberiumShadow** [comment]
Those rules are my personal ones
