### ISSUE TITLE
Insult command.

### ISSUE THREAD

**Issue by Stitch07** [eslachance/komada-pieces#77]
I've seen most people using insult in the fun commands as (prefix)insult [mention]. That's how I thought was the correct way. But I've seen people using it as a string too. So I've seen 2 cases:

1) !insult Soumil
=> Soumil, you know what? You're nothing but a ....

2) !insult Corporate idiots from Louisiana
=> Corporate, you know what? You're nothing but a ...

It's only taking the first word. Can this be fixed?

**Comment by kyranet** [comment]
Show usage and usageDelim from your `exports.help`.

**Comment by CyberiumShadow** [comment]
It has been 7 days without an answer, this issue will now be closed due to lack of response from OP
