### ISSUE TITLE
Bug: didyoumean monitor

### ISSUE THREAD

**Issue by Skillz4Killz** [eslachance/komada-pieces#80]
I had a couple of issues with this monitor.

1) Tried downloading and it never downloaded over 15 minutes long. Console showed npm install completed in about 10 seconds. package.json was also updated. However, the file was never downloaded and the bot was stuck on saying Loading Monitors. It is hours later and still, that message says Loading Monitors.

2) I finally managed to get it installed by doing download the third time. After which I discovered some more errors with it. I believe these errors may be occurring only in 0.20.5, nonetheless, I think it is worth reporting. 

Line 7: ```const conf = client.configuration.get(msg.guild);``` This calls something called configuration but configuration is undefined.

**Comment by CyberiumShadow** [comment]
Point 1 was already discussed with you on the support channel, `pm2 --watch` will leave the message saying `Loading Monitors` as it now has no idea what to edit/ it's a blank slate

Point 2 occurs because the pieces will **most likely** be outdated for Komada Indev and only work for Komada 0.19.7

**Comment by kyranet** [comment]
Actually Cyber, all the pieces are retrocompatible, with exception of the ones which uses the configuration system (KConfigs vs SettingGateway)

**Comment by Skillz4Killz** [comment]
So is it confirmed that this monitor is not compatible due to the SettingGateway? Is there any way someone could update the file with perhaps a comment to show anyone like me using the beta on how to convert it so it is SettingGateway friendly please

**Comment by kyranet** [comment]
Exactly, it's not compatible because of SettingGateway, but it goes much further: It uses methods and properties from 0.18.1-0.19.7 that are not longer in Komada since 0.20.0.

Currently I'm very busy, but if you want to use it and you don't know how to fix it, I'll try to find a way to make it work, and I'll attach it in a comment so people who use indev can use the link instead and get a fully working piece. 

However, the methods that are used to reproduce what DidYouMean does has changed in the last commits, so I can't ensure it'll work completely in the future.

**Comment by Skillz4Killz** [comment]
Leave it be then. Don't worry too much it was just a cool addition I was hoping had a small fix for the new settings.

**Comment by kyranet** [comment]
The DidYouMean piece will be rewritten along all the pieces for an update, soon.

**Comment by kyranet** [comment]
In the current architecture from Komada 0.20.x (and also Klasa), this piece is not longer viable as this makes Komada parse the prefix and command twice.

**Comment by kyranet** [comment]
This piece got modified in #98, test it and let me know if it works.

**Comment by kyranet** [comment]
No response, I'll close this. Feel free to re-open if you have any issue.
