### ISSUE TITLE
Banner and fml commands not downloading properly

### ISSUE THREAD

**Issue by Skillz4Killz** [eslachance/komada-pieces#84]
Not sure if this was just an issue for me but thought I would report it anyway just in case.

1) Both commands were not able to be downloaded after multiple tries and gave no response like an error(this went wrong) or even the loading message that normally appears wasn't there.
2) After trying multiple times I checked the console and realized that they were both failing to install a dependency.
Banner was failing figlet
fml was failing fast-html-parser

It provided no input to me to even check the console log for errors, which might be really nice to have though, to be honest.

3) After doing npm install figlet fast-html-parser --save both commands were able to be successfully downloaded.

**Comment by CyberiumShadow** [comment]
![](https://cdn.discordapp.com/attachments/339944237305036812/346433641326313472/unknown.png)
![](https://cdn.discordapp.com/attachments/339944237305036812/346433742518353933/unknown.png)

**Comment by kyranet** [comment]
Althought it's confirmed this error happens, this issue does not belong to komada-pieces, but to komada itself.

There's also the probability to do the same move as Klasa and remove the download command, since it's rarely used. Feel free to report an issue in the Komada repository.
