### ISSUE TITLE
Bug: Quiz is not taking answers

### ISSUE THREAD

**Issue by Skillz4Killz** [eslachance/komada-pieces#90]
I had many reports on this from my bot users that the quiz command was not taking any answers correct or wrong. It just keeps saying `Seems no one got it! Oh Well`. I tested this myself as well and indeed the bot will not take the correct answer. If the answer is typed correctly it replies `Seems no one got it! Oh Well!`

https://cdn.discordapp.com/attachments/291973192510341120/349030506442129409/unknown.png

**Comment by ghost** [comment]
If  you have answers which are strings, are you writing them (in your code) with any uppercase letters? If so, make them lowercase to fix it.

**Comment by MrJacz** [comment]
@Skillz4Killz Your issue is you need to lowercase the question and anwsers or it will not work

**Comment by CyberiumShadow** [comment]
Solved by community.
The Pieces may be updated/fixed at a later date
