### ISSUE TITLE
Music Commands Errors

### ISSUE THREAD

**Issue by EmersonShatouhy1** [eslachance/komada-pieces#91]
For the music commands, if the bot is playing in one guild, it won't allow music to be played in any other guild as it says it is already playing.

**Comment by kyranet** [comment]
In a much more advanced version of the music module (see [Sneyra](https://github.com/kyranet/Sneyra)'s repository), using a very similar system, this issue is not reproduceable by me.

**Comment by CyberiumShadow** [comment]
@SuperSheep123 please provide reproductions steps and relevant code snippets if possible

**Comment by Stitch07** [comment]
I've seen this happening. PR #95 should fix it.

**Comment by kyranet** [comment]
Fixed by #95
